# Test your FastAPI endpoints

GET http://127.0.0.1:8011/
Accept: application/json

###

GET http://127.0.0.1:8011/hello/User
Accept: application/json

###
POST http://localhost:8011/prescriptions
Accept: application/json