# Test your FastAPI endpoints

GET http://127.0.0.1:8022/
Accept: application/json

###

GET http://127.0.0.1:8022/hello/User
Accept: application/json

###
POST http://localhost:8022/prescriptions
Accept: application/json